#!/usr/bin/bash		
# source <File Path>
if [ -e DBMS ]
then
	clear
	echo "DATABASE MANGEMENT SYSTEM IS UP"
	cd Menu
	source ./mainMenu
else
	mkdir DBMS
	if [ $? -eq 0 ]
	then
			clear
			echo "DATABASE MANGEMENT SYSTEM IS UP "
			cd Menu
			source ./mainMenu
	else
			echo "FAILED TO CREATE DATABASE FOLDER PLEASE CHECK THE PRMINTIONS OF THE CURR DIR "
	fi
fi





