#!/usr/bin/bash		
# source <File Path>
$secandline;
selectDataTypeMenu(){   
               select option in Integer String exist
                do
                    case $option in
                        "Integer")
                        secandline+="String$1"
                            break
                           ;;
                       "String")
                        secandline+="Integer$1"
                            break
                           ;;
                        "exist")
                            secandline+="String$1"
                            echo "setting value to be String..."
                            break
                            ;;
                        *)
                            echo "invalid output"
                    esac
                done
}