#!/usr/bin/bash		
# source <File Path>
$secandline;
selectDataTypeMenu(){   
               select option in Integer String 
                do
                    case $option in
                        "Integer")
                        secandline+="Integer$1"
                            break
                           ;;
                       "String")
                        secandline+="String$1"
                            break
                           ;;
                        *)
                            echo "invalid input please select 1,2 or 3 from the list"
                    esac
                done
}