#!/usr/bin/bash		
# source <File Path>

echo  -e "please enter the of name Datebase and sure make that the name : \n 1)starts with a char \n 2)does not contain any with spaces or spical special character\n"
read -p "MAIN MENU/CREATE > " name

			if [[ $name =~ ^[a-zA-Z][a-zA-Z0-9]*$ ]]
			then
				found=$(find ../DBMS -name $name)
					if [[ -n $found ]]
					then 
						echo 'MAIN MENU/CREATE > this database alreay exists try another name'
					else
						mkdir ../DBMS/$name
						if [ $? -eq 0 ]
						then
						echo "MAIN MENU/CREATE > database created successfully... going back to the mian menu"
						fi	
					fi 

			else
				echo "the name you enterned doesn't match the pattern try agian : "
				source ./create
			fi	
