#!/usr/bin/bash		
PS3="MAIN MENU > "

select option in 'create a database' 'select a database' 'list all databases' 'drop a database' 'exit'
do
	case $option in
		"create a database")
			PS3="CREATE"
			./Menu/create
			;;
		"select a database")	
			echo 'select a database'
			;;
		"list all databases")	
				DBS=$(ls DBMS)
				echo $DBS
			;;
		"drop a database")	
			echo 'drop a database'
			;;	
		"exit")	
			echo 'good bye'
			break
			;;
	esac
done

